### PR TITLE
Implement sleep list

### PR DESCRIPTION
**Pull request by deontologician**
This adds some bits to work with sleep lists etc.

I added a little bit of extra error handling while I was debugging. Let me know if I should take that out or alter it

### CODE REVIEW

**Review by mvertescher — APPROVED** [review]
LGTM!

**Comment by mvertescher** [comment]
Thanks for adding this @deontologician !

**Comment by deontologician** [comment]
Yeah, thanks a lot for writing this. I was disappointed that the swagger definitions I found out there were missing all of the response types

**Comment by cezaris13** [comment]
Small question. The debug flag used in lib.rs:
image
makes all warnings that variables are not used as errors while running `cargo run ...`/ `cargo run`: 
image

How this should be handled?

**Pull request merged**
